name: CD

on:
  release:
    types: [published]

jobs:
  publish:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: gem build --output=release.gem

      - name: Publish gem
        run: gem push release.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
